[pytest]
addopts = -ra -q --alluredir=reports/allure-results --clean-alluredir --html=reports/report.html --self-contained-html
python_files = tests/test_*.py
markers =
    smoke: smoke tests
    regression: regression tests
